name: Release

on:
  push:
    branches: [ master ]

jobs:
  init_release:
    runs-on: ubuntu-latest
    outputs:
       upload_url: ${{ steps.create_draft.outputs.upload_url }}
       version: ${{ steps.create_version.outputs.version }}
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
      
    - name: Install dependencies
      run: dotnet restore
      working-directory: src
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: src
      
    - name: Release - Create Draft for Release
      id: create_draft
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate version - Cut away the first letter (v)
      id: create_version
      run: |
        tag_name=${{ steps.create_draft.outputs.tag_name }}
        echo "::set-output name=version::$(echo ${tag_name:1})"

  build_exec:
    runs-on: ubuntu-latest
    needs: [init_release]
    strategy:
      matrix:
        os: [win-x64, linux-x64, osx-x64]
        configuration: [Release]
        project: [AWSIPRangeRouteCreator]
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Publish ${{ matrix.os }} ${{ matrix.configuration }} - dotnet publish 
      working-directory: src/${{ matrix.project }}
      #New in NET5: PublishSingleFile procudces more than one file... (IncludeNativeLibrariesForSelfExtract fixes that, https://github.com/dotnet/runtime/issues/36590#issuecomment-699257013)
      run: dotnet publish -c ${{ matrix.configuration }} -r ${{ matrix.os }} -p:PublishSingleFile=true -p:DebugType=None -p:IncludeNativeLibrariesForSelfExtract=true -p:Version=${{ needs.init_release.outputs.version }}

    - name: Pack ${{ matrix.os }} - Zip
      working-directory: src/${{ matrix.project }}/bin/${{ matrix.configuration }}/net5.0/${{ matrix.os }}/publish/
      run: zip -r ${{ matrix.project }}.zip .

    - name: Release ${{ matrix.os }} - Upload Release Asset
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.init_release.outputs.upload_url }} 
        asset_path: ./src/${{ matrix.project }}/bin/${{ matrix.configuration }}/net5.0/${{ matrix.os }}/publish/${{ matrix.project }}.zip
        asset_name: ${{ matrix.project }}-${{ matrix.os }}.zip
        asset_content_type: application/zip
